### PR TITLE
Update dependencies.

### LINKED ISSUE #36: Update dependencies
This adapter's dependencies need to be updated in order for it to work with Node v10.

* `serialport` has had a major version bump, but it _shouldn't_ cause any issues. [CHANGELOG](https://github.com/node-serialport/node-serialport/blob/master/packages/serialport/CHANGELOG.md)
* `openzwave-shared` has had a minor version bump, but there were (potentially) breaking changes to `enablePoll()` and `disablePoll()` (see [README](https://github.com/OpenZWave/node-openzwave-shared))

### PR DESCRIPTION
**Pull request by mrstegeman**
Fixes #36

### CODE REVIEW

**Comment by mrstegeman** [comment]
@dhylands Here's a start, at least. It seems like `libopenzwave` is crashing when the adapter starts up, though.

**Comment by dhylands** [comment]
I tried this PR and it seems to load fine on my development machine, I needed to use package.sh to build the dependencies though (rather than yarn) otherwise it will crash trying to load libopenzwave.so due to a missing symbol.

**Comment by mrstegeman** [comment]
Ah, good call! I got it to work this way as well.

So, the main change was to `enablePoll()`. Here's a link to the API diff: https://github.com/OpenZWave/node-openzwave-shared/commit/5f38c0b964b0ebaffc50e6de3a4aa5bc4f861eff#diff-bcb85d3be3a5159f4af9f42750c89c00R104

**Comment by mrstegeman** [comment]
@dhylands Done.

**Comment by dhylands** [comment]
And you should probably bump the version in package.json

**Pull request merged**
